language: php
sudo: false
services:
- mysql
php:
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
before_script:
- cp .env.test .env
- composer self-update
- composer install --ignore-platform-reqs --no-interaction --prefer-dist
- php artisan key:generate
- mysql -e 'create database sherlocks;'
- php artisan migrate
script:
- phpunit
notifications:
  webhooks:
    urls:
    - https://bde.utt.fr/pay/deploy
    on_failure: never
    on_start: never
    on_pull_requests: false
  slack:
    secure: boo7jIA3zjPdL8WPsEpi2+/w/H3YgMwxTtDgrwyT4/xEVNT2f5IrTP2/Y6yECzmNYY67591tlgx8VbdpXqAuLcumaVHiri3xOdyshda0cW+cOswWav+BteLCscQ3Ll9XQGvf+QtuFVNjQ43K1LAvYuxzxnfgP54nhpkvfvlUvy1LBNKQgA0P0acKvydMPKNynheViWaKm8FqDWUTzc48byMd7IP7N+E7Vlx/czMM+v/kubGONO3hxesGvPCUYqDsEzYPqtdwWzoWWxFW4FrKPJLTxzsjIeeOKkPmMz1E/pvOQmwQ3z4irJlCu3xKxdhtiyYhQsJbI098ot2B0Ns7mrSVBhqOHll0oos+TktXMNynGQzbTEV8ddEQ9pmEwyLQ5YAsivP3iYYvC18i8dmwAbQOibr+0cyjWildayCZm/MfslBWVK961gMUImlhQZ41TkkQMmqcaYRo6+7JPP7T3ZjrPr3JRz9IlH+ksrJxZ0M1sl9nIJoVwFnwUBWtcdN5dtRyUusSSCYq5/qf3wtPYNn3Gj/4CvhRIXc7veyvzFPcpBKyZcR2/E2N2Ik+OXhB1o6vCKqgtiWEQKRY5pIaQE1UCOIZ+q3YBrQpol4+hnX41tHJ5wRUXmUU0aH/oRJMLU2w2nw8LZBKI8TQq+18Uzd8p+sSoUsQUjFFNF41PFk=
